### ISSUE TITLE
Font doesn't match GitHub

### ISSUE THREAD

**Issue by sdaitzman** [lukedmor/ghmarkdown#6]
The font should be Helvetica Neue. GitHub uses this CSS:

``` css
font-family: "Helvetica Neue", Helvetica, "Segoe UI", Arial, freesans, sans-serif;
font-size: 16px;
line-height: 1.6;
```

I'm not quite sure how to add this :stuck_out_tongue_winking_eye: I'm working on it in my fork but I'm sure you're much better with Python. If this is super-simple, you should add it! Love the tool.

**Comment by lorepozo** [comment]
Good catch! It was a tiny fix with css scope, everything was there for it otherwise. Thanks! Be sure to upgrade your installation:

``` bash
sudo pip install ghmarkdown --upgrade
```
